# DigitalOcean App Platform Configuration
# This file configures EchoTune AI for one-click deployment on DigitalOcean App Platform
name: echotune-ai
region: nyc

# Static assets (optional)
static_sites:
- name: static
  source_dir: /static
  routes:
  - path: /static

# Main web service
services:
- name: web
  # Source configuration
  source_dir: /
  github:
    repo: primoscope/doved
    branch: main
    deploy_on_push: true
  
  # Build configuration
  build_command: |
    echo "🚀 Building EchoTune AI..."
    npm ci --only=production
    echo "✅ Build complete!"
  
  # Runtime configuration  
  run_command: "npm start"
  
  # Network configuration
  http_port: 3000
  
  # Health check
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  # Resource allocation
  instance_count: 1
  instance_size_slug: basic-xxs
  
  # Auto-scaling (optional)
  autoscaling:
    min_instance_count: 1
    max_instance_count: 3
    metrics:
    - type: cpu_utilization
      value:
        average_utilization: 70
  
  # Environment configuration
  environment_slug: node-js
  
  # Environment variables
  envs:
  # Application settings
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
  - key: LOG_LEVEL
    value: info
  - key: DEBUG
    value: "false"
  - key: TRUST_PROXY
    value: "true"
  
  # Feature flags
  - key: HEALTH_CHECK_ENABLED
    value: "true"
  - key: METRICS_ENABLED
    value: "true"
  - key: CHAT_ENABLED
    value: "true"
  - key: DEMO_MODE
    value: "true"
  - key: DEFAULT_LLM_PROVIDER
    value: mock
  
  # User-configurable secrets (optional)
  - key: SPOTIFY_CLIENT_ID
    value: ""
    type: SECRET
  - key: SPOTIFY_CLIENT_SECRET  
    value: ""
    type: SECRET
  - key: GEMINI_API_KEY
    value: ""
    type: SECRET
  - key: OPENAI_API_KEY
    value: ""
    type: SECRET
  - key: MONGODB_URI
    value: ""
    type: SECRET
  
  # Computed environment variables
  - key: FRONTEND_URL
    value: "${APP_URL}"
  - key: DOMAIN
    value: "${APP_DOMAIN}"
  - key: SPOTIFY_REDIRECT_URI
    value: "${APP_URL}/auth/callback"

# Worker service for background tasks (optional)
workers:
- name: health-monitor
  source_dir: /
  github:
    repo: primoscope/doved
    branch: main
  
  run_command: |
    echo "🔍 Starting health monitor..."
    while true; do
      curl -f http://web:3000/health >/dev/null 2>&1 && echo "✅ Health OK" || echo "❌ Health check failed"
      sleep 300
    done
  
  instance_count: 1
  instance_size_slug: basic-xxs
  
  environment_slug: node-js

# Jobs for one-time tasks (optional)  
jobs:
- name: setup
  source_dir: /
  github:
    repo: primoscope/doved
    branch: main
  
  run_command: |
    echo "🔧 Running initial setup..."
    echo "✅ Setup complete!"
  
  instance_count: 1
  instance_size_slug: basic-xxs
  environment_slug: node-js
  kind: PRE_DEPLOY

# Database (optional - can be added later)
# databases:
# - name: echotune-db
#   engine: MONGODB
#   version: "6"
#   size: db-s-1vcpu-1gb

# Domains (auto-configured by DigitalOcean)
domains:
- domain: echotune-ai-${RANDOM_STRING}.ondigitalocean.app
  type: PRIMARY