filename: Code Refactoring Advisor
description: Identifies refactoring opportunities and suggests code quality improvements for maintainable, scalable code
model: gpt-4o
modelParameters:
  temperature: 0.4
  max_tokens: 1800
messages:
  - role: system
    content: |
      You are a code refactoring expert specializing in improving TypeScript/JavaScript codebases for maintainability, readability, and performance.
      
      Focus on identifying:
      1. **Code Smells**: Long methods, duplicate code, complex conditionals, large classes
      2. **Design Patterns**: Opportunities to apply SOLID principles and design patterns
      3. **Performance**: Algorithmic improvements, memory optimizations, async patterns
      4. **Maintainability**: Code organization, naming, separation of concerns
      5. **Type Safety**: Better TypeScript usage, generic patterns, type guards
      6. **Modern Features**: ES6+ features, latest TypeScript capabilities
      
      Provide specific refactoring steps with before/after code examples.
  - role: user
    content: |
      Analyze the following code for refactoring opportunities:
      
      **Module:** {{moduleName}}
      **Code Quality Issues:** {{qualityIssues}}
      **Performance Concerns:** {{performanceConcerns}}
      **Maintainability Goals:** {{maintainabilityGoals}}
      
      **Current Code:**
      ```{{language}}
      {{currentCode}}
      ```
      
      **Usage Context:** {{usageContext}}
      **Constraints:** {{constraints}}
      
      Please identify:
      - Code smells and design issues
      - Performance optimization opportunities
      - Type safety improvements
      - Modern language feature adoption
      - Design pattern applications
      - Separation of concerns improvements
      
      Provide refactored code with explanations and migration steps.
testData:
  - moduleName: "PDF Generation Service"
    qualityIssues: "Large methods, mixed responsibilities, poor error handling"
    performanceConcerns: "Synchronous file operations, memory usage during PDF generation"
    maintainabilityGoals: "Better separation of concerns, improved testability, cleaner error handling"
    language: "typescript"
    usageContext: "High-throughput PDF generation service with multiple templates"
    constraints: "Must maintain backward compatibility, minimize dependencies"
    currentCode: |
      export class PDFService extends GSDataSource {
        async generatePDF(ctx: GSContext, template: string, data: any): Promise<GSStatus> {
          try {
            // Validate input
            if (!template || typeof template !== 'string') {
              return new GSStatus(false, 400, 'Invalid template');
            }
            
            if (!data || typeof data !== 'object') {
              return new GSStatus(false, 400, 'Invalid data');
            }
            
            // Create document
            const doc = new PDFDocument();
            let filename = 'document.pdf';
            
            // Generate filename
            if (data.fullName) {
              filename = data.fullName.replace(/\s+/g, '_') + '_' + template + '.pdf';
            } else if (data.filename) {
              filename = data.filename;
            } else {
              filename = 'document_' + Date.now() + '.pdf';
            }
            
            // Sanitize filename
            filename = filename.replace(/[^a-zA-Z0-9._-]/g, '');
            
            const outputPath = path.join('generated_docs', filename);
            
            // Generate content based on template
            if (template === 'tuition_receipt') {
              doc.fontSize(20).text('Tuition Receipt', { align: 'center' });
              doc.fontSize(12).text(`Student: ${data.fullName || 'N/A'}`);
              doc.text(`Amount: $${data.tuitionAmount || 0}`);
              doc.text(`Due Date: ${data.dueDate || 'N/A'}`);
            } else if (template === 'transcript') {
              doc.fontSize(20).text('Official Transcript', { align: 'center' });
              doc.fontSize(12).text(`Student: ${data.fullName || 'N/A'}`);
              doc.text(`Student ID: ${data.studentId || 'N/A'}`);
            } else {
              return new GSStatus(false, 400, 'Unknown template');
            }
            
            // Save document
            const stream = fs.createWriteStream(outputPath);
            doc.pipe(stream);
            doc.end();
            
            await new Promise((resolve, reject) => {
              stream.on('finish', resolve);
              stream.on('error', reject);
            });
            
            return new GSStatus(true, 200, 'PDF generated', { filename, path: outputPath });
          } catch (error) {
            console.error('PDF generation failed:', error);
            return new GSStatus(false, 500, 'Internal error');
          }
        }
      }
    expected: |
      ## Code Refactoring Analysis
      
      ### 🔍 Identified Issues:
      
      1. **Large Method (70+ lines)** - Single method handles validation, filename generation, content creation, and file saving
      2. **Mixed Responsibilities** - Business logic mixed with file operations and validation
      3. **Poor Type Safety** - Using `any` type, no input validation interfaces
      4. **Code Duplication** - Template-specific logic could be extracted
      5. **Synchronous File Operations** - Potential performance bottleneck
      6. **Poor Error Handling** - Generic error messages, no specific error types
      
      ### 🛠️ Refactored Implementation:
      
      ```typescript
      // Domain Types
      interface StudentData {
        readonly fullName: string;
        readonly studentId?: string;
        readonly tuitionAmount?: number;
        readonly dueDate?: Date;
        readonly filename?: string;
      }
      
      interface PDFGenerationResult {
        readonly filename: string;
        readonly path: string;
        readonly size: number;
      }
      
      // Error Types
      class PDFGenerationError extends Error {
        constructor(message: string, public readonly code: number) {
          super(message);
          this.name = 'PDFGenerationError';
        }
      }
      
      // Template Strategy Pattern
      interface PDFTemplate {
        generate(doc: PDFDocument, data: StudentData): void;
        validateData(data: StudentData): boolean;
      }
      
      class TuitionReceiptTemplate implements PDFTemplate {
        generate(doc: PDFDocument, data: StudentData): void {
          doc.fontSize(20).text('Tuition Receipt', { align: 'center' });
          doc.moveDown();
          doc.fontSize(12)
            .text(`Student: ${data.fullName}`)
            .text(`Amount: $${data.tuitionAmount?.toFixed(2) ?? '0.00'}`)
            .text(`Due Date: ${data.dueDate?.toLocaleDateString() ?? 'N/A'}`);
        }
        
        validateData(data: StudentData): boolean {
          return !!(data.fullName && data.tuitionAmount);
        }
      }
      
      class TranscriptTemplate implements PDFTemplate {
        generate(doc: PDFDocument, data: StudentData): void {
          doc.fontSize(20).text('Official Transcript', { align: 'center' });
          doc.moveDown();
          doc.fontSize(12)
            .text(`Student: ${data.fullName}`)
            .text(`Student ID: ${data.studentId ?? 'N/A'}`);
        }
        
        validateData(data: StudentData): boolean {
          return !!(data.fullName && data.studentId);
        }
      }
      
      // Template Factory
      class TemplateFactory {
        private static templates = new Map<string, PDFTemplate>([
          ['tuition_receipt', new TuitionReceiptTemplate()],
          ['transcript', new TranscriptTemplate()]
        ]);
        
        static getTemplate(templateName: string): PDFTemplate | null {
          return this.templates.get(templateName) ?? null;
        }
        
        static getSupportedTemplates(): string[] {
          return Array.from(this.templates.keys());
        }
      }
      
      // Utility Services
      class FilenameGenerator {
        static generate(data: StudentData, template: string): string {
          if (data.filename) {
            return this.sanitize(data.filename);
          }
          
          if (data.fullName) {
            const safeName = data.fullName.replace(/\s+/g, '_');
            return this.sanitize(`${safeName}_${template}.pdf`);
          }
          
          return `document_${Date.now()}.pdf`;
        }
        
        private static sanitize(filename: string): string {
          return filename
            .replace(/[^a-zA-Z0-9._-]/g, '')
            .substring(0, 255); // Limit filename length
        }
      }
      
      class FileManager {
        static async savePDF(doc: PDFDocument, outputPath: string): Promise<number> {
          return new Promise((resolve, reject) => {
            const stream = fs.createWriteStream(outputPath);
            let totalBytes = 0;
            
            stream.on('finish', () => resolve(totalBytes));
            stream.on('error', reject);
            
            doc.on('data', (chunk: Buffer) => {
              totalBytes += chunk.length;
            });
            
            doc.pipe(stream);
            doc.end();
          });
        }
      }
      
      // Validation Service
      class InputValidator {
        static validateTemplate(template: string): void {
          if (!template || typeof template !== 'string') {
            throw new PDFGenerationError('Template name is required', 400);
          }
          
          if (!TemplateFactory.getTemplate(template)) {
            const supported = TemplateFactory.getSupportedTemplates().join(', ');
            throw new PDFGenerationError(
              `Unknown template '${template}'. Supported: ${supported}`, 
              400
            );
          }
        }
        
        static validateStudentData(data: unknown): StudentData {
          if (!data || typeof data !== 'object') {
            throw new PDFGenerationError('Student data is required', 400);
          }
          
          const studentData = data as StudentData;
          
          if (!studentData.fullName || typeof studentData.fullName !== 'string') {
            throw new PDFGenerationError('Student full name is required', 400);
          }
          
          return studentData;
        }
      }
      
      // Main Service (Refactored)
      export class PDFService extends GSDataSource {
        async generatePDF(
          ctx: GSContext, 
          templateName: string, 
          rawData: unknown
        ): Promise<GSStatus<PDFGenerationResult>> {
          try {
            // Validate inputs
            InputValidator.validateTemplate(templateName);
            const studentData = InputValidator.validateStudentData(rawData);
            
            // Get template and validate data compatibility
            const template = TemplateFactory.getTemplate(templateName)!;
            if (!template.validateData(studentData)) {
              throw new PDFGenerationError(
                `Data validation failed for template '${templateName}'`, 
                400
              );
            }
            
            // Generate PDF
            const result = await this.createPDF(template, studentData, templateName);
            
            return new GSStatus(true, 200, 'PDF generated successfully', result);
            
          } catch (error) {
            if (error instanceof PDFGenerationError) {
              return new GSStatus(false, error.code, error.message);
            }
            
            console.error('Unexpected PDF generation error:', error);
            return new GSStatus(false, 500, 'Internal server error');
          }
        }
        
        private async createPDF(
          template: PDFTemplate, 
          data: StudentData, 
          templateName: string
        ): Promise<PDFGenerationResult> {
          const doc = new PDFDocument();
          const filename = FilenameGenerator.generate(data, templateName);
          const outputPath = path.join('generated_docs', filename);
          
          // Generate content
          template.generate(doc, data);
          
          // Save file asynchronously
          const fileSize = await FileManager.savePDF(doc, outputPath);
          
          return {
            filename,
            path: outputPath,
            size: fileSize
          };
        }
      }
      ```
      
      ### 🚀 Key Improvements:
      
      #### 1. **Single Responsibility Principle**
      - `InputValidator`: Handles all input validation
      - `TemplateFactory`: Manages template creation and discovery
      - `FilenameGenerator`: Generates and sanitizes filenames
      - `FileManager`: Handles file operations
      
      #### 2. **Strategy Pattern for Templates**
      - Extensible template system
      - Template-specific validation
      - Easy to add new templates
      
      #### 3. **Enhanced Type Safety**
      - Strong typing with interfaces
      - Custom error types
      - Generic GSStatus return type
      
      #### 4. **Better Error Handling**
      - Specific error types and codes
      - Proper error context
      - Distinguishes between user and system errors
      
      #### 5. **Performance Improvements**
      - Asynchronous file operations
      - Memory-efficient streaming
      - File size tracking
      
      ### 📋 Migration Steps:
      
      1. **Phase 1**: Extract validation logic
      2. **Phase 2**: Implement template strategy pattern
      3. **Phase 3**: Add utility services (filename, file management)
      4. **Phase 4**: Update error handling
      5. **Phase 5**: Add comprehensive tests
      
      ### 📊 Benefits:
      - **Maintainability**: +90% (clear separation of concerns)
      - **Testability**: +85% (isolated components)
      - **Type Safety**: +95% (strict typing throughout)
      - **Performance**: +25% (async operations)
      - **Extensibility**: +80% (easy to add templates)
evaluators:
  - name: Code smells identified
    string:
      contains: "Identified Issues"
  - name: Design patterns applied
    string:
      contains: "Strategy Pattern"
  - name: Refactored code provided
    string:
      contains: "Refactored Implementation"
  - name: Migration steps included
    string:
      contains: "Migration Steps"
  - name: Benefits quantified
    string:
      contains: "Benefits"