name: Gemini Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Gemini AI Code Reviewer
        uses: truongnh1992/gemini-ai-code-reviewer@v6.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: gemini-2.5-flash-lite # optional, default is gemini-1.5-flash-002
          INPUT_EXCLUDE: ""
