name: Workflow Status Notifications
'on':
  workflow_run:
    workflows:
      - EchoTune AI - Optimized CI/CD Pipeline
    types:
      - completed
jobs:
  notify-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Notify workflow completion
        run: |-
          echo "Workflow completed: ${{ github.event.workflow_run.name }}"
          echo "Status: ${{ github.event.workflow_run.conclusion }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"

          # Add notification logic here (Slack, Discord, etc.)
          if [ "${{ github.event.workflow_run.conclusion }}" = "failure" ]; then
            echo "🔴 Workflow failed - notification sent"
          else
            echo "✅ Workflow completed successfully"
          fi
